### ISSUE TITLE
Getting maven exception while build the code

### ISSUE THREAD

**Issue by GuruvaiahG** [jhipster/jhipster-dashboard#2]
NFO] --- spring-boot-maven-plugin:1.4.0.RELEASE:repackage (default) @ jhipster-dashboard ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.585 s
[INFO] Finished at: 2017-12-12T09:33:04+05:30
[INFO] Final Memory: 33M/325M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.4.0.RELEASE:repackage (default) on project jhipster-dashboard: Execution default of goal org.springframework.boot:spring-boot-maven-plugin:1.4.0.RELEASE:repackage failed: A required class was missing while executing org.springframework.boot:spring-boot-maven-plugin:1.4.0.RELEASE:repackage: org/springframework/asm/ClassVisitor
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.springframework.boot:spring-boot-maven-plugin:1.4.0.RELEASE
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/guruvaiah/.m2/repository/org/springframework/boot/spring-boot-maven-plugin/1.4.0.RELEASE/spring-boot-maven-plugin-1.4.0.RELEASE.jar
[ERROR] urls[1] = file:/C:/Users/guruvaiah/.m2/repository/org/springframework/boot/spring-boot-loader-tools/1.4.0.RELEASE/spring-boot-loader-tools-1.4.0.RELEASE.jar
[ERROR] urls[2] = file:/C:/Users/guruvaiah/.m2/repository/org/springframework/spring-core/4.3.2.RELEASE/spring-core-4.3.2.RELEASE.jar
[ERROR] urls[3] = file:/C:/Users/guruvaiah/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
[ERROR] urls[4] = file:/C:/Users/guruvaiah/.m2/repository/org/apache/maven/maven-archiver/2.6/maven-archiver-2.6.jar
[ERROR] urls[5] = file:/C:/Users/guruvaiah/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.7/maven-shared-utils-0.7.jar
[ERROR] urls[6] = file:/C:/Users/guruvaiah/.m2/repository/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.jar
[ERROR] urls[7] = file:/C:/Users/guruvaiah/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.21/plexus-interpolation-1.21.jar
[ERROR] urls[8] = file:/C:/Users/guruvaiah/.m2/repository/org/eclipse/aether/aether-util/1.0.2.v20150114/aether-util-1.0.2.v20150114.jar
[ERROR] urls[9] = file:/C:/Users/guruvaiah/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[10] = file:/C:/Users/guruvaiah/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
[ERROR] urls[11] = file:/C:/Users/guruvaiah/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar
[ERROR] urls[12] = file:/C:/Users/guruvaiah/.m2/repository/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar
[ERROR] urls[13] = file:/C:/Users/guruvaiah/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[14] = file:/C:/Users/guruvaiah/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.0.0.M5/org.eclipse.sisu.inject-0.0.0.M5.jar
[ERROR] urls[15] = file:/C:/Users/guruvaiah/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[16] = file:/C:/Users/guruvaiah/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[17] = file:/C:/Users/guruvaiah/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[18] = file:/C:/Users/guruvaiah/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/1.4/maven-common-artifact-filters-1.4.jar
[ERROR] urls[19] = file:/C:/Users/guruvaiah/.m2/repository/org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.jar
[ERROR] urls[20] = file:/C:/Users/guruvaiah/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar
[ERROR] urls[21] = file:/C:/Users/guruvaiah/.m2/repository/commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.jar
[ERROR] urls[22] = file:/C:/Users/guruvaiah/.m2/repository/com/google/collections/google-collections/1.0/google-collections-1.0.jar
[ERROR] urls[23] = file:/C:/Users/guruvaiah/.m2/repository/junit/junit/4.12/junit-4.12.jar
[ERROR] urls[24] = file:/C:/Users/guruvaiah/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
[ERROR] urls[25] = file:/C:/Users/guruvaiah/.m2/repository/org/codehaus/plexus/plexus-archiver/2.8.1/plexus-archiver-2.8.1.jar
[ERROR] urls[26] = file:/C:/Users/guruvaiah/.m2/repository/org/codehaus/plexus/plexus-io/2.3.2/plexus-io-2.3.2.jar
[ERROR] urls[27] = file:/C:/Users/guruvaiah/.m2/repository/org/apache/commons/commons-compress/1.9/commons-compress-1.9.jar
[ERROR] urls[28] = file:/C:/Users/guruvaiah/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar
[ERROR] urls[29] = file:/C:/Users/guruvaiah/.m2/repository/org/apache/maven/plugins/maven-shade-plugin/2.2/maven-shade-plugin-2.2.jar
[ERROR] urls[30] = file:/C:/Users/guruvaiah/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
[ERROR] urls[31] = file:/C:/Users/guruvaiah/.m2/repository/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
[ERROR] urls[32] = file:/C:/Users/guruvaiah/.m2/repository/asm/asm/3.3.1/asm-3.3.1.jar
[ERROR] urls[33] = file:/C:/Users/guruvaiah/.m2/repository/asm/asm-commons/3.3.1/asm-commons-3.3.1.jar
[ERROR] urls[34] = file:/C:/Users/guruvaiah/.m2/repository/asm/asm-tree/3.3.1/asm-tree-3.3.1.jar
[ERROR] urls[35] = file:/C:/Users/guruvaiah/.m2/repository/org/jdom/jdom/1.1/jdom-1.1.jar
[ERROR] urls[36] = file:/C:/Users/guruvaiah/.m2/repository/org/apache/maven/shared/maven-dependency-tree/2.1/maven-dependency-tree-2.1.jar
[ERROR] urls[37] = file:/C:/Users/guruvaiah/.m2/repository/org/vafer/jdependency/0.7/jdependency-0.7.jar
[ERROR] urls[38] = file:/C:/Users/guruvaiah/.m2/repository/commons-io/commons-io/1.3.2/commons-io-1.3.2.jar
[ERROR] urls[39] = file:/C:/Users/guruvaiah/.m2/repository/asm/asm-analysis/3.2/asm-analysis-3.2.jar
[ERROR] urls[40] = file:/C:/Users/guruvaiah/.m2/repository/asm/asm-util/3.2/asm-util-3.2.jar
[ERROR] urls[41] = file:/C:/Users/guruvaiah/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------: org.springframework.asm.ClassVisitor
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

**Comment by jdubois** [comment]
I just did a `mvn clean compile` and I had no problem building the code.

Closing as this is probably a config issue on your side (proxy, JDK, whatever.... you don't give any information anyway)

**Comment by GuruvaiahG** [comment]
Try with mvn clean install

**Comment by GuruvaiahG** [comment]
don't close directly

**Comment by jdubois** [comment]
Also no problem with `mvn clean install`

**Comment by jdubois** [comment]
I'm sorry but you don't give enough information to reproduce

**Comment by pascalgrimaud** [comment]
No problem for me too. Everything works fine, and I'm on the train.
Here an extract of my logs:

```
19:45:38 in ~/tmp 
➜ git clone https://github.com/jhipster/jhipster-dashboard.git
Clonage dans 'jhipster-dashboard'...
remote: Counting objects: 90, done.
Dépaquetage des objets: 100% (90/90), fait.
remote: Total 90 (delta 0), reused 0 (delta 0), pack-reused 90

19:45:43 in ~/tmp 
➜ cd jhipster-dashboard 

19:45:47 in ~/tmp/jhipster-dashboard on  master 
➜ ./mvnw clean install 
Downloading https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.3.9/apache-maven-3.3.9-bin.zip
..............................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /home/pgrimaud/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9-bin.zip to /home/pgrimaud/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2
Set executable permissions for: /home/pgrimaud/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/bin/mvn
[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/1.4.0.RELEASE/spring-boot-starter-parent-1.4.0.RELEASE.pom

(...)

Downloaded: https://repo.maven.apache.org/maven2/log4j/log4j/1.2.12/log4j-1.2.12.jar (350 KB at 512.0 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/junit/junit/3.8.2/junit-3.8.2.jar (118 KB at 162.1 KB/sec)
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/pgrimaud/tmp/jhipster-dashboard/target/classes
[WARNING] /home/pgrimaud/tmp/jhipster-dashboard/src/main/java/io/github/jhipster/dashboard/JHipsterDashboard.java: /home/pgrimaud/tmp/jhipster-dashboard/src/main/java/io/github/jhipster/dashboard/JHipsterDashboard.java uses or overrides a deprecated API.
[WARNING] /home/pgrimaud/tmp/jhipster-dashboard/src/main/java/io/github/jhipster/dashboard/JHipsterDashboard.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ jhipster-dashboard ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/pgrimaud/tmp/jhipster-dashboard/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ jhipster-dashboard ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ jhipster-dashboard ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.6:jar (default-jar) @ jhipster-dashboard ---
[INFO] Building jar: /home/pgrimaud/tmp/jhipster-dashboard/target/jhipster-dashboard-0.0.1-SNAPSHOT.jar
[INFO] 
[INFO] --- spring-boot-maven-plugin:1.4.0.RELEASE:repackage (default) @ jhipster-dashboard ---
Downloading: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-loader-tools/1.4.0.RELEASE/spring-boot-loader-tools-1.4.0.RELEASE.pom
Downloaded: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-loader-tools/1.4.0.RELEASE/spring-boot-loader-tools-1.4.0.RELEASE.pom (5 KB at 16.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-loader-tools/1.4.0.RELEASE/spring-boot-loader-tools-1.4.0.RELEASE.jar
Downloaded: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-loader-tools/1.4.0.RELEASE/spring-boot-loader-tools-1.4.0.RELEASE.jar (139 KB at 558.9 KB/sec)
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ jhipster-dashboard ---
[INFO] Installing /home/pgrimaud/tmp/jhipster-dashboard/target/jhipster-dashboard-0.0.1-SNAPSHOT.jar to /home/pgrimaud/.m2/repository/io/github/jhipster/jhipster-dashboard/0.0.1-SNAPSHOT/jhipster-dashboard-0.0.1-SNAPSHOT.jar
[INFO] Installing /home/pgrimaud/tmp/jhipster-dashboard/pom.xml to /home/pgrimaud/.m2/repository/io/github/jhipster/jhipster-dashboard/0.0.1-SNAPSHOT/jhipster-dashboard-0.0.1-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 52.931 s
[INFO] Finished at: 2017-12-12T19:47:09+01:00
[INFO] Final Memory: 37M/252M
[INFO] ------------------------------------------------------------------------

19:47:10 in ~/tmp/jhipster-dashboard on  master took 1m 5s 
➜ 
```
